---
# tasks file for elasticsearch
- name: Update all packages to their latest version
  apt:
    update_cache: yes
    force_apt_get: yes
- name: Installing the java version8
  apt:
    name: '{{ JDK_version  }}'
- name: get apt repo key
  apt_key:
    url: '{{ public_signing_key  }}'
    state: present
- name: INSTALLING REQUIRED PACKAGES
  apt:
    pkg: '{{ packages }}'
- name: Add elasticsearch repository
  apt_repository:
    repo: '{{ elasticsearch_repo }}'
- name: install logstash
  apt:
    name: filebeat
    state: present
    update_cache: yes
# Replace default filebeat.yml

- name: Replace default filebeat.yml
  template:
   src: filebeat.yml
   dest: /etc/filebeat/filebeat.yml
- name: Starting filebeat
  service:
   name: filebeat
   state: restarted
   enabled: yes
