---
# tasks file for kibana
- name: Update all packages to their latest version
  apt:
    update_cache: yes
    force_apt_get: yes
- name: Installing the java version8
  apt:
    name: '{{ JDK_version  }}'
- name: get apt repo key
  apt_key:
    url: '{{ public_signing_key  }}'
    state: present
- name: INSTALLING REQUIRED PACKAGES
  apt:
    pkg: '{{ packages }}'
- name: Add elasticsearch repository
  apt_repository:
    repo: '{{ kibana_repo }}'
- name: install kibana
  apt:
    name: kibana
    state: present
    update_cache: yes
# Replace default kibana.yml

- name: Replace default kibana.yml
  template:
   src: kibana.yml
   dest: /etc/kibana/kibana.yml
- name: Starting Kibana
  service:
   name: kibana
   state: started
   enabled: yes
